version: 2.1

# Recover cache for all jobs
restore_cache: &restore_cache
  restore_cache:
    keys:
      - dependency-cache-{{ checksum "build.gradle" }}-{{ checksum  "autoproxy-annotations/build.gradle" }}-{{ checksum  "autoproxy-generators/build.gradle" }}-{{ checksum  "autoproxy-processor/build.gradle" }}-{{ checksum  "autoproxy-rx-annotations/build.gradle" }}-{{ checksum  "autoproxy-rx-generators/build.gradle" }}
      - processor-{{ .Revision }}
      - annotations-{{ .Revision }}
      - generators-{{ .Revision }}
      - rx-annotations-{{ .Revision }}
      - rx-generators-{{ .Revision }}
      # fallback to using the latest cache if no exact match is found
      - dependency-cache-

environment:
  # Customize the JVM maximum heap limit
  JVM_OPTS: -Xmx3200m
  TERM: dumb

jobs:
  # Download all dependencies
  dependencies:
    working_directory: ~/autoproxy
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - *restore_cache
      - run: # version
          name: Version Autogenerate
          command: bash gradle/version-up.sh
      - run: # dependencies
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon
      - save_cache: # dependencies
          paths:
            - ~/.gradle
          key: dependency-cache-{{ checksum "build.gradle" }}-{{ checksum  "autoproxy-annotations/build.gradle" }}-{{ checksum  "autoproxy-generators/build.gradle" }}-{{ checksum  "autoproxy-processor/build.gradle" }}-{{ checksum  "autoproxy-rx-annotations/build.gradle" }}-{{ checksum  "autoproxy-rx-generators/build.gradle" }}
          
  # DEBUG binaries
  debug:
    working_directory: ~/autoproxy
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - *restore_cache
      - run: # version
          name: Version Autogenerate
          command: bash gradle/version-up.sh
      - run: # build
          name: Compile Debug Binaries
          command: ./gradlew assembleDebug

  # RELEASE binaries
  release:
    working_directory: ~/autoproxy
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - *restore_cache
      - run: # version
          name: Version Autogenerate
          command: bash gradle/version-up.sh
      - run: # build
          name: Compile Release Binaries
          command: ./gradlew assemble
      - store_artifacts: # annotations
          path: ~/autoproxy-annotations/build/libs
          destination: libs
      - store_artifacts: # generator
          path: ~/autoproxy-generators/build/libs
          destination: libs
      - store_artifacts: # processor
          path: ~/autoproxy-processor/build/libs
          destination: libs
      - store_artifacts: # rx-annotations
          path: ~/autoproxy-rx-annotations/build/libs
          destination: libs
      - store_artifacts: # rx-generators
          path: ~/autoproxy-rx-generators/build/libs
          destination: libs
      - save_cache: # annotations
          paths:
            - ~/autoproxy-annotations/build
          key: annotations-{{ .Revision }}    
      - save_cache: # generator
          paths:
            - ~/autoproxy-generators/build
          key: generators-{{ .Revision }}
      - save_cache: # processor
          paths:
            - ~/autoproxy-processor/build
          key: processor-{{ .Revision }}    
      - save_cache: # rx-annotations
          paths:
            - ~/autoproxy-rx-annotations/build
          key: rx-annotations-{{ .Revision }}
      - save_cache: # rx-generators
          paths:
            - ~/autoproxy-rx-generators/build
          key: rx-generators-{{ .Revision }}

  # Unit Tests
  # https://circleci.com/docs/2.0/configuration-reference/#store_test_results
  test:
    working_directory: ~/autoproxy
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - *restore_cache
      - run: # version
          name: Version Autogenerate
          command: bash gradle/version-up.sh
      - run: # tests
          name: Run unit tests
          command: ./gradlew test
      - run: # collect results
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: ~/test-results/junit

  # Lint
  lint:
    working_directory: ~/autoproxy
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - *restore_cache
      - run: # version
          name: Version Autogenerate
          command: bash gradle/version-up.sh
      - run: # lint
          name: Run Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports

  # Deploy
  deploy:
    working_directory: ~/autoproxy
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - *restore_cache
      - run: # version
          name: Version Autogenerate
          command: bash gradle/version-up.sh
      - run: # lint
          name: Run Lint
          command: ./gradlew lint

#
# https://circleci.com/docs/2.0/workflows/
#          
workflows:
  version: 2
  quick_build:
    jobs:
      - dependencies
      - debug:
          requires:
            - dependencies
      - lint:
          requires:
            - debug
  warmup_cache_weekly: # keep our cache always warm
    jobs:
      - dependencies
    triggers:
      - schedule: # https://crontab.guru/#0_0_*_*_* - every day
          cron: "0 0 * * *" 
          filters:
            branches:
              only:
                - master
  build_test_deploy:
    jobs:
      - dependencies:
          filters:
            branches:
              only:
                - master
      - debug:
          requires:
            - dependencies
      - release:
          requires:
            - dependencies
      - lint:
          requires:
            - debug
      - test:
          requires:
            - release
            - debug
      - gatekeeper:
          type: approval
          requires:
            - test
            - lint
      - deploy:
          requires:
            - gatekeeper
  tag_build_test_deploy:
    jobs:
      - dependencies:
          filters:
            tags: # 1.0 ... 1.0.1.1
              only: /^[0-9]+\.[0-9]+.*/
      - debug:
          requires:
            - dependencies
      - release:
          requires:
            - dependencies
      - lint:
          requires:
            - debug
      - test:
          requires:
            - release
            - debug
      - gatekeeper:
          type: approval
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - gatekeeper

# References:
#   https://github.com/asksven/BetterBatteryStats/blob/master/circle.yml
#   https://github.com/santaevpavel/ClipboardTranslator/blob/master/.circleci/config.yml
#   https://github.com/unhappychoice/DroidFlyer/blob/master/.circleci/config.yml
#